# Configurações do Servidor
server.port=8080

# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtracker_db
spring.datasource.username=seu_usuario_postgres
spring.datasource.password=sua_senha_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
# 'update' cria ou atualiza as tabelas automaticamente com base nas suas Entidades (ideal para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true